/*MIGRAMOS EN EL SIGUIENTE ORDEN:*/
/*1. USUARIOS*/
INSERT INTO users (id, created_at, email, name, provider, role, password) VALUES
(1, '2026-08-21', 'prueba@musicmarket.com', 'Usuario Prueba', 'LOCAL', 'USER', NULL),
(2, '2026-08-24', 'nuevo@musicmarket.com', 'Usuario Nuevo', 'LOCAL', 'USER', '$2a$10$0MxRcKXDMpyIRU2prtDDlONYr3pAWWEAnKP0NJ7sv1uIaPbMi.HOa'),
(5, '2026-08-24', 'admin@musicmarket.com', 'Administrador', 'LOCAL', 'SUPER_ADMIN', '$2a$10$Ymq.3lkOZBFQN4o6zBlzXeBS.0DIJEKd7R8MsmL5HKdgxlG5kI.n.'),
(3, '2026-08-24', 'antonio.ortega@musicmarket.com', 'Antonio Ortega', 'LOCAL', 'ADMIN', '$2a$10$cAG170cB/o7lcWwM74wihOs8viIG8VPd1KNHp.2qCqhTrYUrmqNQ6'),
(6, '2026-08-28', 'antonio@musicmarket.com', 'antonio', 'LOCAL', 'USER', '$2a$10$6Twq7cEXUJbh2cLlK7PtsuEoe.cx5bgzfxggBlSLUOgd6t0WyUkR2');

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1), true);

/*2. PUBLICACIONES*/

INSERT INTO publications (id, album_name, artist, condition, created_at, description, genre, image_uris, name, price, release_year, format, user_id) VALUES
(2, 'Rubber Soul', 'The Beatles', 'EXCELLENT', '2026-08-04', 'Sixth studio album by The Beatles, marking their artistic evolution. Features classics like Norwegian Wood, In My Life, and Michelle. Original 1965 pressing.', 'Rock', ARRAY['https://www.thebeatles.com/sites/default/files/styles/max_2600x2600/public/2021-06/Rubber%20Soul.jpg?itok=P8DYZM6d'], 'Rubber Soul - The Beatles', 79.98, 1965, 'Vinilo', 2),
(3, 'Caifanes', 'Caifanes', 'VERY_GOOD', '2026-08-04', 'Debut album of the iconic Mexican rock band Caifanes. Released in 1988, featuring hits like Mátenme Porque Me Muero and La Negra Tomasa. A cornerstone of Latin American rock.', 'Rock en Español', ARRAY['https://www.caifanes.com.mx/assets/extra-images/disco001.jpg'], 'Caifanes - Caifanes', 42.99, 1988, 'Vinilo', 2),
(4, 'Rumours', 'Fleetwood Mac', 'NEAR_MINT', '2026-08-04', 'One of the best-selling albums of all time. A masterpiece of 70s soft rock featuring classics like Dreams, Go Your Own Way, and The Chain.', 'Soft Rock', ARRAY['https://upload.wikimedia.org/wikipedia/en/f/fb/FMacRumours.PNG'], 'Rumours - Fleetwood Mac', 45.00, 1977, 'Vinilo', 2),
(5, 'Thriller', 'Michael Jackson', 'MINT', '2026-08-04', 'The best-selling album of all time featuring legendary hits like Billie Jean, Beat It, and Thriller. A pop masterpiece produced by Quincy Jones.', 'Pop', ARRAY['https://upload.wikimedia.org/wikipedia/en/5/55/Michael_Jackson_-_Thriller.png'], 'Thriller - Michael Jackson', 56.00, 1982, 'Vinilo', 1),
(6, 'Random Access Memories', 'Daft Punk', 'EXCELLENT', '2026-08-22', 'Edición en vinilo de Random Access Memories.', 'Electronic', ARRAY['https://upload.wikimedia.org/wikipedia/en/2/26/Daft_Punk_-_Random_Access_Memories.png?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=original'], 'Random Access Memories', 35.99, 2013, 'Vinilo', 1),
(7, 'Toxicity', 'System Of A Down', 'EXCELLENT', '2026-08-22', 'Toxicity es el segundo álbum de estudio de la banda armenio-estadounidense de heavy metal System of a Down. Publicado el 4 de septiembre de 2001 por American Recordings, este CD tuvo gran éxito internacional, al vender más de 12 millones de copias a nivel mundial, y dio a conocer a la banda en todo el mundo. Fue asimismo el primer álbum de la banda en liderar las listas de éxitos, y ha sido certificado con seis discos de platino en los Estados Unidos.[2] Forma parte de la lista de los 100 discos que debes tener antes del fin del mundo, publicada en 2012 por Sony Music. La revista Rolling Stone colocó el álbum en el puesto #44 en su lista de los mejores álbumes de la década del 2000.[3] Asimismo, en 2017 lo posicionó en el puesto #27 en su lista "The 100 Greatest Metal Albums of All Time".[4] En enero de 2025, la misma publicación elaboró su lista de los 250 mejores álbumes del siglo XXI, y Toxicity fue uno de los dos únicos álbumes de música metal incluidos y el mejor posicionado (en el puesto 159).', 'Rock', ARRAY['https://upload.wikimedia.org/wikipedia/en/6/64/SystemofaDownToxicityalbumcover.jpg?_=20220822153945'], 'Toxicity - SOAD Excelentes Condiciones', 89.99, 2001, 'Vinilo', 2),
(8, 'Discovery', 'Daft Punk', 'VERY_GOOD', '2026-08-22', 'Segunda producción de estudio de Daft Punk, publicada en 2001. Edición en CD en muy buenas condiciones.', 'Electronic', ARRAY['https://upload.wikimedia.org/wikipedia/en/2/27/Daft_Punk_-_Discovery.png?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=original'], 'Discovery - Daft Punk', 29.99, 2001, 'CD', 1),
(9, 'Are You Experienced (Vinyl) [Importado] - Nuevo de paquete', 'Jimmy Hendrix', 'MINT', '2026-08-28', 'Descripción del producto\nAre You Experienced es el álbum de estudio debut de la banda de rock inglés-americana Jimi Hendrix Experience.\n\nDetalles del producto\nProducto descontinuado por el fabricante ‏ : ‎ No\nDimensiones del producto ‏ : ‎ 30,48 x 32 x 2,54 cm; 272,16 g\nFabricante ‏ : ‎ Legacy Recordings\nNúmero de modelo del producto ‏ : ‎ 28940204\nFecha de lanzamiento original ‏ : ‎ 2014\nTiempo de ejecución ‏ : ‎ 41 minutos\nEtiqueta ‏ : ‎ Legacy Recordings\nASIN ‏ : ‎ B00JFVORBI\nPaís de origen ‏ : ‎ Estados Unidos\nNúmero de discos ‏ : ‎ 1\nClasificación en los más vendidos de Amazon: nº3,219 en Música (Ver el Top 100 en Música)\nnº18 en Arena Rock\nOpiniones de los clientes: 4.6 4.6 de 5 estrellas   (3,454)', 'Rock', ARRAY['https://m.media-amazon.com/images/I/81Umxm8x4qL._AC_SX385_.jpg'], 'Are You Experienced (Vinyl) [Importado]', 20.00, 1967, 'Vinilo', 6),
(10, 'Master of Puppets', 'Metallica', 'EXCELLENT', '2026-08-29', 'Tercer álbum de estudio de Metallica, publicado en 1986. Uno de los discos más representativos del thrash metal y el último álbum de estudio de la banda con Cliff Burton.', 'Metal', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Metallica_-_Master_of_Puppets_cover.jpg'], 'Master of Puppets - Metallica', 64.99, 1986, 'Vinilo', 1),
(11, 'Nevermind', 'Nirvana', 'NEAR_MINT', '2026-08-29', 'Segundo álbum de estudio de Nirvana. Una de las producciones más influyentes del movimiento grunge de los años noventa.', 'Grunge', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/NirvanaNevermindalbumcover.jpg'], 'Nevermind - Nirvana', 48.50, 1991, 'Vinilo', 1),
(12, 'The Dark Side of the Moon', 'Pink Floyd', 'MINT', '2026-08-29', 'Álbum clásico de Pink Floyd publicado en 1973. Edición en vinilo nueva y en excelentes condiciones.', 'Progressive Rock', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Dark_Side_of_the_Moon.png'], 'The Dark Side of the Moon - Pink Floyd', 74.99, 1973, 'Vinilo', 1),
(13, 'Hybrid Theory', 'Linkin Park', 'VERY_GOOD', '2026-08-29', 'Álbum debut de Linkin Park publicado en 2000. Incluye temas como In the End, Crawling y One Step Closer.', 'Nu Metal', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Linkin_Park_Hybrid_Theory_Album_Cover.jpg'], 'Hybrid Theory - Linkin Park', 24.99, 2000, 'CD', 1),
(14, 'Dookie', 'Green Day', 'GOOD', '2026-08-29', 'Tercer álbum de estudio de Green Day. Un clásico del punk rock de los años noventa.', 'Punk Rock', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Green_Day_-_Dookie_cover.jpg'], 'Dookie - Green Day', 18.50, 1994, 'Cassette', 1),
(15, 'A Night at the Opera', 'Queen', 'NEAR_MINT', '2026-08-29', 'Cuarto álbum de estudio de Queen. Incluye uno de los temas más conocidos de la banda: Bohemian Rhapsody.', 'Rock', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Queen_A_Night_At_The_Opera.png'], 'A Night at the Opera - Queen', 58.00, 1975, 'Vinilo', 2),
(16, 'Canción Animal', 'Soda Stereo', 'EXCELLENT', '2026-08-29', 'Quinto álbum de estudio de Soda Stereo, publicado en 1990. Incluye clásicos del rock en español como De Música Ligera.', 'Rock en Español', ARRAY['https://coverartarchive.org/release/43500162-0628-431f-90e4-8417eec3b6b5/front-500'], 'Canción Animal - Soda Stereo', 49.99, 1990, 'Vinilo', 2),
(17, 'Re', 'Café Tacvba', 'VERY_GOOD', '2026-08-29', 'Segundo álbum de estudio de Café Tacvba y uno de los trabajos más representativos del rock alternativo mexicano.', 'Rock en Español', ARRAY['https://i.pinimg.com/736x/32/1c/83/321c83ba6c493c4c2c89d9591582c4d1.jpg'], 'Re - Café Tacvba', 34.50, 1994, 'CD', 2),
(18, 'AM', 'Arctic Monkeys', 'MINT', '2026-08-29', 'Quinto álbum de estudio de Arctic Monkeys. Edición en vinilo en condición impecable.', 'Indie Rock', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Arctic_Monkeys_-_AM.png'], 'AM - Arctic Monkeys', 42.99, 2013, 'Vinilo', 2),
(19, 'Demon Days', 'Gorillaz', 'EXCELLENT', '2026-08-29', 'Segundo álbum de estudio de Gorillaz. Incluye canciones como Feel Good Inc. y DARE.', 'Alternative', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Gorillaz_Demon_Days.PNG'], 'Demon Days - Gorillaz', 27.99, 2005, 'CD', 2),
(20, 'Disintegration', 'The Cure', 'NEAR_MINT', '2026-08-29', 'Octavo álbum de estudio de The Cure. Una de las producciones más reconocidas de la banda británica.', 'Alternative Rock', ARRAY['https://elevenstore.cl/elevenstore/7423-thickbox_default/the-cure-disintegration-cd.jpg'], 'Disintegration - The Cure', 52.00, 1989, 'Vinilo', 3),
(21, 'OK Computer', 'Radiohead', 'EXCELLENT', '2026-08-29', 'Tercer álbum de estudio de Radiohead. Edición en vinilo muy bien conservada.', 'Alternative Rock', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Radioheadokcomputer.png'], 'OK Computer - Radiohead', 59.99, 1997, 'Vinilo', 3),
(22, 'Appetite for Destruction', 'Guns N'' Roses', 'VERY_GOOD', '2026-08-29', 'Álbum debut de Guns N'' Roses. Incluye clásicos como Welcome to the Jungle, Paradise City y Sweet Child o'' Mine.', 'Hard Rock', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/GunsnRosesAppetiteforDestructionalbumcover.jpg'], 'Appetite for Destruction - Guns N'' Roses', 41.50, 1987, 'CD', 3),
(23, 'The Number of the Beast', 'Iron Maiden', 'GOOD', '2026-08-29', 'Tercer álbum de estudio de Iron Maiden y una de las producciones más conocidas de la banda.', 'Heavy Metal', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Iron_Maiden_-_The_Number_Of_The_Beast.jpg'], 'The Number of the Beast - Iron Maiden', 29.99, 1982, 'Cassette', 3),
(24, 'Californication', 'Red Hot Chili Peppers', 'MINT', '2026-08-29', 'Séptimo álbum de estudio de Red Hot Chili Peppers, publicado en 1999 y producido por Rick Rubin.', 'Alternative Rock', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/RedHotChiliPeppersCalifornication.jpg'], 'Californication - Red Hot Chili Peppers', 46.90, 1999, 'Vinilo', 3),
(25, 'Violator', 'Depeche Mode', 'EXCELLENT', '2026-08-29', 'Séptimo álbum de estudio de Depeche Mode. Incluye temas como Personal Jesus y Enjoy the Silence.', 'Electronic', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Depeche_Mode_-_Violator.png'], 'Violator - Depeche Mode', 44.99, 1990, 'Vinilo', 6),
(26, 'Ten', 'Pearl Jam', 'VERY_GOOD', '2026-08-29', 'Álbum debut de Pearl Jam publicado en 1991. Una pieza fundamental del movimiento grunge.', 'Grunge', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/PearlJam-Ten2.jpg'], 'Ten - Pearl Jam', 31.99, 1991, 'CD', 6),
(27, 'Is This It', 'The Strokes', 'NEAR_MINT', '2026-08-29', 'Álbum debut de The Strokes. Una de las producciones más influyentes del revival del garage rock.', 'Indie Rock', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/The_Strokes_-_Is_This_It_cover.png'], 'Is This It - The Strokes', 39.50, 2001, 'Vinilo', 6),
(28, 'Memo Rex Commander y el Corazón Atómico de la Vía Láctea', 'Zoé', 'EXCELLENT', '2026-08-29', 'Cuarto álbum de estudio de Zoé. Uno de los discos más representativos de la banda mexicana.', 'Rock en Español', ARRAY['https://coverartarchive.org/release/b04bd1d3-058d-43f9-b3b9-6101c0c1c8d5/front-500'], 'Memo Rex Commander - Zoé', 36.99, 2006, 'CD', 6),
(29, 'Romance', 'Luis Miguel', 'MINT', '2026-08-29', 'Octavo álbum de estudio de Luis Miguel. Producción dedicada principalmente a boleros clásicos.', 'Bolero', ARRAY['https://coverartarchive.org/release/08c12ec8-1bac-4e56-bc40-e0d24e7ee163/front-500'], 'Romance - Luis Miguel', 28.50, 1991, 'Cassette', 6),
(30, '1989', 'Taylor Swift', 'NEAR_MINT', '2026-08-29', 'Quinto álbum de estudio de Taylor Swift y uno de sus trabajos de mayor reconocimiento internacional.', 'Pop', ARRAY['https://en.wikipedia.org/wiki/Special:FilePath/Taylor_Swift_-_1989.png'], '1989 - Taylor Swift', 43.99, 2014, 'Vinilo', 6),
(31, 'When We All Fall Asleep, Where Do We Go?', 'Billie Eilish', 'EXCELLENT', '2026-08-29', 'Álbum debut de Billie Eilish. Incluye canciones como Bad Guy, Bury a Friend y When the Party''s Over.', 'Alternative Pop', ARRAY['https://i.ebayimg.com/images/g/FaQAAOSw6jRmPeku/s-l1200.jpg'], 'When We All Fall Asleep, Where Do We Go? - Billie Eilish', 38.99, 2019, 'CD', 6);


/*3. COMENTARIOS*/
INSERT INTO comments (id, content, created_at, publication_id, user_id) VALUES
(1, 'Me interesa.', '2026-08-25', 7, 2),
(2, 'A mi tambien me ineresa.', '2026-08-25', 7, 3),
(3, 'A mi más.', '2026-08-25', 7, 2),
(4, 'Sigue disponible!', '2026-08-27', 4, 2),
(5, 'Me interea', '2026-08-27', 8, 5),
(8, 'hola', '2026-08-28', 9, 6);

/*4. FAVORITOS*/
INSERT INTO favorites (id, publication_id, user_id) VALUES
(1, 5, 1),
(2, 7, 1),
(3, 8, 1),
(4, 3, 5),
(6, 3, 1);